import {neon} from '@neondatabase/serverless';
import {defaults,type Preferences,type Job,salaryInfo} from './matching';
export function runtime(){return process.env;}
export async function db(){const url=process.env.DATABASE_URL;if(!url)throw Error('Database is not connected. Add DATABASE_URL in Vercel and redeploy.');const sql=neon(url);await sql`CREATE TABLE IF NOT EXISTS records (key TEXT PRIMARY KEY, value TEXT NOT NULL)`;return sql;}
export async function read<T>(key:string,fallback:T):Promise<T>{const sql=await db();const rows=await sql`SELECT value FROM records WHERE key=${key}`;return rows[0]?JSON.parse(rows[0].value):fallback;}
export async function write(key:string,value:unknown){const sql=await db();await sql`INSERT INTO records(key,value) VALUES(${key},${JSON.stringify(value)}) ON CONFLICT(key) DO UPDATE SET value=excluded.value`;}
export function authorize(req:Request){if(req.method!=='GET'){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw Error('Invalid request origin');}}
export function failure(e:unknown){const message=e instanceof Error?e.message:'Request failed.';const safe=/^(Unauthorized|Invalid |Enter |Maximum |Email |Database is not connected|Add your|Job not found|Job sources|Unknown action|A job source)/.test(message)?message:'Request failed. Check your database and email configuration in Vercel.';return Response.json({error:safe},{status:message==='Unauthorized'?401:message==='Invalid request origin'?403:400});}
export async function prefs(){return read<Preferences>('preferences',defaults);}
export function emailStatus(){return {senderReady:!!(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM),schedulerReady:!!(process.env.CRON_SECRET&&process.env.CRON_SECRET.length>=16&&process.env.VERCEL_ENV==='production')};}
function clean(s:unknown){return String(s??'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
function safeUrl(s:unknown){try{const u=new URL(String(s));return u.protocol==='https:'?u.href:''}catch{return ''}}
export async function fetchJobs(){const cached=await read<{jobs:Job[];updated:string;warnings:string[]}|null>('feed',null);if(cached&&Date.now()-Date.parse(cached.updated)<6*3600000)return cached;const jobs:Job[]=[];const warnings:string[]=[];const sources=await Promise.allSettled([fetch('https://remotive.com/api/remote-jobs',{signal:AbortSignal.timeout(20000)}).then(async r=>{if(!r.ok)throw Error('Remotive unavailable');const d=await r.json() as {jobs:Record<string,unknown>[]};if(!Array.isArray(d.jobs))throw Error('Invalid Remotive response');return d.jobs.map(j=>({id:'remotive-'+j.id,title:clean(j.title),company:clean(j.company_name),location:clean(j.candidate_required_location),remote:true,salary:clean(j.salary),...salaryInfo(clean(j.salary)),published:String(j.publication_date).replace(/Z$/,'')+'Z',url:safeUrl(j.url),source:'Remotive',description:clean(j.description).slice(0,2200),type:clean(j.job_type).replaceAll('_',' ')}))}),fetch('https://www.arbeitnow.com/api/job-board-api',{signal:AbortSignal.timeout(20000)}).then(async r=>{if(!r.ok)throw Error('Arbeitnow unavailable');const d=await r.json() as {data:Record<string,unknown>[]};if(!Array.isArray(d.data))throw Error('Invalid Arbeitnow response');return d.data.map(j=>({id:'arbeitnow-'+j.slug,title:clean(j.title),company:clean(j.company_name),location:clean(j.location),remote:j.remote===true,salary:'',...salaryInfo(''),published:new Date(Number(j.created_at)*1000).toISOString(),url:safeUrl(j.url),source:'Arbeitnow',description:clean(j.description).slice(0,2200),type:'Not specified'}))})]);sources.forEach((r,i)=>{if(r.status==='fulfilled')jobs.push(...r.value);else warnings.push((i?'Arbeitnow':'Remotive')+' is temporarily unavailable.');});if(sources.every(r=>r.status==='rejected')){if(cached)return {...cached,warnings:['Sources unavailable. Showing previously fetched jobs.']};throw Error('Job sources are unavailable. Please try again later.');}const seen=new Set<string>();const result={jobs:jobs.filter(j=>{const key=(j.company+'|'+j.title+'|'+j.location).toLowerCase();if(!j.url||seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>Date.parse(b.published)-Date.parse(a.published)),updated:new Date().toISOString(),warnings};await write('feed',result);return result;}
